#!/bin/bash

# Clone existing configuration files from https://gitlab.com/cit2420/2420-as2-starting-filesin a directory called config_files
# If git not installed, send an error and exit code 1
git clone https://gitlab.com/cit2420/2420-as2-starting-files ~/config_files || echo "You either don't have git installed or the repository has been made private or deleted" ; exit 1

# Get a list of full paths to directories in the cloned repository, excluding hidden directories
directories=$(find ~/config_files -maxdepth 1 -mindepth 1 -type d -not -path "*/.*")

# Iterate through the directories variable
for path in ${directories[@]}; do

  # Use the find command on each full path in $directories to find subdirectories
  for dir in $(find $path -maxdepth 0 -type d);do
    # Get the basename of each subdirectory found
    base="${dir##*/}"

    # Check the basename against cases defined below
    case "$base" in

      # If basename == bin, iterate through the files and create symbolic links in ~/bin that point to the scripts in ~/config_files/bin directory
      bin)
        for script in $(find $dir -maxdepth 1 -mindepth 1 -type f); do
          ln -s $script ~/bin
        done
        ;;

      # If basename == config, iterate through its subdirectories and create symbolic links in the ~/.config directory that point to the directories in ~/config_files/config directory 
      config)
        for config_dir in $(find $dir -maxdepth 1 -mindepth 1 -type d); do
          base="${config_dir##*/}"
          ln -s $config_dir ~/.config
        done
        ;;

      # If basename == home, iterate through the files and create symbolic links in the user's home directory that point to the files in ~/config_files/home directory
      home)
        for file in $(find $dir -maxdepth 1 -mindepth 1 -type f); do
          base="${file##*/}"
          ln -s $file ~/.$base
        done
        ;;

      # If basename is not part of the defined case statements in this script, tell the user to edit the script
      *)
        echo -e "***\nNew directory in the repository since this script (configsetup) was last modified
Edit script to accomodate it\n***"
        ;;
    esac
  done
done

echo "Configuration file setup complete"
