#!/bin/bash

# The purpose of this script is to install packages from a user defined list on a new system

# Storing the contents of the package-list plain text file in a variable
packages=$(cat ./package-list)

# Run Arch Linux package manager along with the packages defined in the package-list plain text file
pacman -S $packages
