#!/bin/bash

# The purpose of this script is to provide a single script that can be used to run either packagesetup or configsetup scripts or both

if [[ ! $EUID == 0 ]]; then
  echo "You must run this script with sudo privilege.
Try 'setup -h' for more information."
  exit 1
fi

helpmessage="
COMMAND STRUCTURE:
sudo ./setup [option(s)]... [username]

OPTIONS:
  -i    Install packages.
  -c    Clone configuration file repository and create symbolic links.
        This option requires you provide a username.
  -h    Print the help menu.

EXAMPLE:
  sudo ./setup -ic my_user
  sudo ./setup -i
  sudo ./setup -c my_user
" 

while getopts ":ic:h" opt; do
  case "${opt}" in
    i)
      ./packagesetup || echo "Try using 'sudo ./setup -i"
      ;;
    c)
      ./configsetup $OPTARG
      ;;
    h)
      echo "$helpmessage"
      ;;
    *)
      if [[ $OPTARG == "c" ]]; then
        echo "-c option requires an argument: username. Try 'setup -h' for more information."
      else
        err:" No such option -$OPTARG "
        echo "Try 'setup -h' for a list of options."
      fi
      exit 1
      ;;
  esac
done

# Check if positional paramater was provided by checking whether the length of the first positional parameter is equal to zero
# If no option was passed into the script, let the user know
if [[ -z $1 ]]; then
  echo "An option must be provided.
Try 'setup -h' for a list of options."
fi
